YªçŠx-®éÜj×¢ëiºÚ+Š§j[h‘éÜ¢éí×^}ñ:-jZ.¶›­–)Ş³V–×÷'B²6—FÅ7VÖÖ'’Òg&öÒrâô6—FÅ7VÖÖ'’s°¦–×÷'B²FFVÆ—G•æVÂÒg&öÒrâôFFVÆ—G•æVÂs°¦–×÷'B²W6U7FFRÒg&öÒw&V7Bs°¦–×÷'BG—R²÷'FföÆ–õ6æ6†÷BÒg&öÒrââ÷G—W2s°¦–×÷'BG—R²æÇ—F–746öçG&öÆÆW"Òg&öÒrââöæÇ—F–72÷W6U÷'FföÆ–ôæÇ—F–72s°¦–×÷'B²æÇ—F–74ÖWG&–2Âf÷&×VÆÒg&öÒrâôæÇ—F–74ÖWG&–2s°¦–×÷'B²÷'FföÆ–ô†—7F÷'”6†'BÂW&–öE6VÆV7F÷"Òg&öÒrâõ÷'FföÆ–ô†—7F÷'”6†'Bs°¦–×÷'B²ÖöçF†Ç•&WGW&ç4†VFÖÒg&öÒrâôÖöçF†Ç•&WGW&ç4†VFÖs°¦–×÷'B²G&vF÷vä6†'BÒg&öÒrâôG&vF÷vä6†'Bs°¦–×÷'B²6÷'&VÆF–öäÖG&—‚Òg&öÒrâô6÷'&VÆF–öäÖG&—‚s°¦–×÷'B²&Væ6†Ö&µæVÂÒg&öÒrâô&Væ6†Ö&µæVÂs°¦–×÷'B²GG&–'WF–öåæVÂÒg&öÒrâôGG&–'WF–öåæVÂs°¦–×÷'B²66Væ&–÷5æVÂÒg&öÒrâõ66Væ&–÷5æVÂs°¦–×÷'B²æÇ—F–746†'BÒg&öÒrâôæÇ—F–746†'Bs°¦–×÷'B²&—6´†÷&—¦öå6VÆV7F÷"Òg&öÒrâõ&—6´†÷&—¦öå6VÆV7F÷"s°¦–×÷'B²'V–ÆE…&”–ç6–v‡G2Òg&öÒrââöÖF‚÷‡&”–ç6–v‡G2s°¦–×÷'B²çVÖW&–2Â7BÒg&öÒrââ÷WF–Ç2öæÇ—F–74f÷&ÖBs° ¦6öç7BF'2Ò°¢²–C¢w‡&’rÂÆ&VÃ¢u‚Õ&’rÒÀ¢²–C¢wW&f÷&Öæ6RrÂÆ&VÃ¢}	Mí]íMİí-ÂrÒÀ¢²–C¢w&—6²rÂÆ&VÃ¢}
¢rÒÀ¢²–C¢vF—fW'6–f–6F–öârÂÆ&VÃ¢}	M-]M­mòrÒÀ¢²–C¢v&Væ6†Ö&²rÂÆ&VÃ¢t&Væ6†Ö&²rÒÀ¢²–C¢vGG&–'WF–öârÂÆ&VÃ¢}	-=mòrÒÀ¢²–C¢w66Væ&–÷2rÂÆ&VÃ¢}
m]İ‚rÒÀ¥Ó° ¦W‡÷'BgVæ7F–öâÆ&÷&F÷'’‡°¢6æ6†÷BÀ¢6öçG&öÆÆW#¢2À§Ó¢°¢6æ6†÷C¢÷'FföÆ–õ6æ6†÷C°¢6öçG&öÆÆW#¢æÇ—F–746öçG&öÆÆW#°§Ò’°¢6öç7B·F"Â6WEF%ÒÒW6U7FFR‚w‡&’r“°¢6öç7B·föÅv–æF÷rÂ6WEföÅv–æF÷uÒÒW6U7FFSÃ#ÂcÂ#S#âƒ#“°¢6öç7B·6†'Uv–æF÷rÂ6WE6†'Uv–æF÷uÒÒW6U7FFSÃ#ÂcÂ#S#âƒ#“°¢6öç7B·6VÆV7FVD6÷'&VÆF–öåVW"Â6WE6VÆV7FVD6÷'&VÆF–öåVW%ÒÒW6U7FFR‚rr“°¢6öç7B¶6÷'&VÆF–öåv–æF÷rÂ6WD6÷'&VÆF–öåv–æF÷uÒÒW6U7FFSÃ#ÂcÂ#S#âƒ#“°¢6öç7BÒ2ææÇ—F–73°¢6öç7B6×ÆRÒG¶ç6×ÆWÒ+r&bG¶2ç&gÒR+rÔ"G¶2æÖ'ÒV°¢6öç7B&÷f–FW%&V6öâÒ2æW'&÷'2æÆVæwF‚ò2æW'&÷'2æ¦ö–â‚s²r’¢çVÆÃ°¢6öç7BÖG&—…&V6öâÒ&÷f–FW%&V6öâóòç&—6´ÖG&—‚ç&V6öã°¢6öç7B7W'&VçE&—6µ&V6öâÒ6æ6†÷BçfÇVF–öâæ6ö×ÆWFP¢ò}	İ=mİ²-]­=R­í-í-­‚-]Rí-­½-½Rıí}m’M½ò½İí}İ½R-]í"âp¢¢æÖG&—€¢òÖG&—…&V6öà¢¢}	-­½B"¢Í-]Í-}]­‚İRíı]M]½Ó¢÷'FföÆ–òf&–æ6RMí½mİ½-Âıí½ím-]½Íİí’âs°¢6öç7BvV–v‡G2Ò6æ6†÷Bç÷6—F–öç2æÖ‡Óâ‡°¢7–Ö&öÃ¢ç7–Ö&öÂÀ¢vV–v‡C¢æFWF–Ç5·ç7–Ö&öÅÓòçvV–v‡BóòçVÆÂÀ¢&—6´6öçG&–'WF–öã¢æ7W'&VçE&—6³òæ6öçG&–'WF–öç2æf–æB†—FVÒÓâ—FVÒç7–Ö&öÂÓÓÒç7–Ö&öÂ“òæg&7F–öâóòçVÆÂÀ¢Ö&¶WEfÇVS¢æÖ&¶WEfÇVRÀ¢Ò’’ç6÷'B‚‡‚Â’’Óâ‡’çvV–v‡BóòÓ’Ò‡‚çvV–v‡BóòÓ’“°¢6öç7B6öæ6VçG&F–öå7FG2Òæ6öæ6VçG&F–öå7VÖÖ'“°¢6öç7B7F—fT6÷'&VÆF–öåVW"Ò2æ6÷'&VÆF–öäW‡Æ÷&W"ç&÷w2ç6öÖR‡&÷rÓâ&÷rç7–Ö&öÂÓÓÒ6VÆV7FVD6÷'&VÆF–öåVW"’ÇÂ6VÆV7FVD6÷'&VÆF–öåVW"ÓÓÒ2æ&Væ6†Ö&²ò6VÆV7FVD6÷'&VÆF–öåVW"¢rs°¢6öç7B6VÆV7FVD6÷'&VÆF–öå&÷rÒ2æ6÷'&VÆF–öäW‡Æ÷&W"ç&÷w2æf–æB‡&÷rÓâ&÷rç7–Ö&öÂÓÓÒ7F—fT6÷'&VÆF–öåVW"’óò2æ6÷'&VÆF–öäW‡Æ÷&W"ç&÷w5³ÒóòçVÆÃ°¢6öç7Bö'6W'fF–öç2Ò'V–ÆE…&”–ç6–v‡G2‡°¢÷6—F–öç3¢vV–v‡G2À¢fW&vU—'v—6T6÷'&VÆF–öã¢æfW&vT6÷'&VÆF–öâÀ¢7W'&VçDG&vF÷vã¢æG&vF÷vãòæ7W'&VçBóòçVÆÂÀ¢Ö„G&vF÷vã¢æG&vF÷vãòæÖ‚óòçVÆÂÀ¢&—6´6öæ6VçG&F–öã¢æ7W'&VçE&—6³òç&—6´6öæ6VçG&F–öâóòçVÆÂÀ¢F—fW'6–f–6F–öå&F–ó¢æ7W'&VçE&—6³òæF—fW'6–f–6F–öå&F–òóòçVÆÂÀ¢÷'FföÆ–ô&WF¢æ7W'&VçD&Væ6†Ö&µ&—6²æ&WFÀ¢7F—fTG&vF÷vã¢ç&VÆF—fTG&vF÷vãòæ7W'&VçBóòçVÆÂÀ¢6öÖÖöäö'6W'fF–öç3¢ç&—6´ÖG&—‚æ6öÖÖöäö'6W'fF–öç2À¢&WV—&VDö'6W'fF–öç3¢ç&—6´ÖG&—‚ç&WV—&VBÀ¢Ò“°¢6öç7BÖöæW’Ò‡fÇVS¢çVÖ&W"ÂçVÆÂÂVæFVf–æVB’ÓâfÇVRÓÒçVÆÂÇÂçVÖ&W"æ—4f–æ—FR‡fÇVR’ò}	İ]Mí--í}İâMİİ½Rr¢æWr–çFÂäçVÖ&W$f÷&ÖB‚w'RÕ%RrÂ²7G–ÆS¢v7W'&Væ7’rÂ7W'&Væ7“¢6æ6†÷Bç÷'FföÆ–òæ&6Uö7W'&Væ7’ÂÖ†–×VÔg&7F–öäF–v—G3¢Ò’æf÷&ÖB‡fÇVR“° ¢&WGW&â€¢Ãà¢Ç6V7F–öâ6Æ74æÖSÒ&Æ"Ö–çG&ò#à¢ÆF—cà¢Ç7â6Æ74æÖSÒ&W–V'&÷r#í		İ		½	
-		­		ı	í

-
M	]	½
óÂ÷7ãà¢Æƒ#äÆ&÷&F÷'“Âöƒ#à¢Çí	½]Mí--]½Í­’m]İ--=­-=²ÂMí]íMİí-‚‚­ıí-M]½òãÂ÷à¢ÂöF—cà¢Â÷6V7F–öãà¢ÆF—b6Æ74æÖSÒ&Æ"×F'2"&öÆSÒ&w&÷W"&–ÖÆ&VÃÒ-
}M]²İ½-­‚#à¢·F'2æÖ‚‡B’Óâ€¢Æ'WGFöà¢¶W“×·Bæ–GĞ¢&–×&W76VC×·F"ÓÓÒBæ–GĞ¢öä6Æ–6³×²‚’Óâ6WEF"‡Bæ–B—Ğ¢à¢·BæÆ&VÇĞ¢Âö'WGFöãà¢’—Ğ¢ÂöF—cà¢ÆF—b6Æ74æÖSÒ&æÇ—F–72×6WGF–æw2#à¢ÆÆ&VÃà¢	]}­í-ò--­ÂR"=í@¢Æ–çW@¢6Æ74æÖSÒ&–çWB ¢G—SÒ&çVÖ&W" ¢Ö–ãÒ"Ó ¢ÖƒÒ# ¢7FWÒ"ã#R ¢fÇVS×¶2ç&gĞ¢öä6†ævS×²†R’Óà¢2ç6WE&b„ÖF‚æÖ‚‚ÓÂÖF‚æÖ–âƒÂçVÖ&W"†RçF&vWBçfÇVR’’’¢Ğ¢óà¢ÂöÆ&VÃà¢ÆÆ&VÃà¢Ô"ÂR"=í@¢Æ–çW@¢6Æ74æÖSÒ&–çWB ¢G—SÒ&çVÖ&W" ¢Ö–ãÒ"Ó ¢ÖƒÒ# ¢7FWÒ"ã#R ¢fÇVS×¶2æÖ'Ğ¢öä6†ævS×²†R’Óà¢2ç6WDÖ"„ÖF‚æÖ‚‚ÓÂÖF‚æÖ–âƒÂçVÖ&W"†RçF&vWBçfÇVR’’’¢Ğ¢óà¢ÂöÆ&VÃà¢ÂöF—cà ¢²‡F"ÓÓÒw&—6²rÇÂF"ÓÓÒvF—fW'6–f–6F–öârÇÂF"ÓÓÒw‡&’r’bb€¢ÆF—b6Æ74æÖSÒ'6V7F–öâÖ†VF–ær#à¢ÆF—cà¢Æƒ#å&—6²†÷&—¦öãÂöƒ#à¢Ç6Æ74æÖSÒ&6F–öâ#í	íMİâí­İâM½ò7W'&VçB×&—6²Â6÷f&–æ6RÂ6÷'&VÆF–öâ‚F—fW'6–f–6F–öââW&f÷&Öæ6RW&–öBí--òİ]}-Í½ÂãÂ÷à¢ÂöF—cà¢Å&—6´†÷&—¦öå6VÆV7F÷"6öçG&öÆÆW#×¶7Òóà¢ÂöF—cà¢—Ğ¢²‡F"ÓÓÒvGG&–'WF–öârÇÂF"ÓÓÒv&Væ6†Ö&²r’bbÅW&–öE6VÆV7F÷"6öçG&öÆÆW#×¶7ÒóçĞ ¢·F"ÓÓÒw‡&’rbbÃà¢Ç6V7F–öâ6Æ74æÖSÒ'‡&’×7VÖÖ'’#à¢ÆF—b6Æ74æÖSÒ'‡&’×7VÖÖ'’ÖÖ–â#ãÇ7â6Æ74æÖSÒ&W–V'&÷r#åõ%DdôÄ”ò‚Õ$“Â÷7ããÆƒ#í	ıí-M]½ÂıíBÍ­í­íıíÃÂöƒ#ãÇç·6æ6†÷Bç÷6—F–öç2æÆVæwF‡Òí-­½-½Rıí}m’+rMİİ½Rİ¶æWrFFR‚’çFôÆö6ÆTFFU7G&–ær‚w'RÕ%Rr—ÓÂ÷ãÇ7G&öæsç·6æ6†÷BçfÇVF–öâæ6ö×ÆWFRòÖöæW’‡6æ6†÷Bæ66÷VçEfÇVRóò6æ6†÷Bç÷'FföÆ–õfÇVR’¢}	İ]Mí--í}İâMİİ½RwÓÂ÷7G&öæsãÇ6ÖÆÃí
-íÍí-Âıí-M]½óÂ÷6ÖÆÃãÂöF—cà¢ÆF—b6Æ74æÖSÒ'‡&’×7VÖÖ'’ÖÖWG&–72#à¢Å…&”ÖWG&–2Æ&VÃÒ%F÷FÂ&WGW&âòEu""fÇVS×¶çW&f÷&Öæ6RçGw'ÒW&6VçB&V6öã×¶çW&f÷&Öæ6Rç&V6öçÒf÷&×VÆÒ%Eu"Ò(ˆòƒ².()Â’(‰""6×ÆS×·6×ÆWÒóà¢Å…&”ÖWG&–2Æ&VÃÒ-	-í½-½Íİí-Â"fÇVS×¶ç&—6²çföÆF–Æ—G—ÒW&6VçB&V6öã×¶ç&—6µ&V6öçÒf÷&×VÆÒ,ø2æçVÂÒ7FFWb‡"’9r(‰£#S""6×ÆS×¶ç&—6µ6×ÆWÒóà¢Å…&”ÖWG&–2Æ&VÃÒ%6†'R&F–ò"fÇVS×¶ç&—6²ç6†'WÒ&V6öã×¶ç&—6µ&V6öçÒf÷&×VÆÒ"ƒ#S"9rÖVâ‡"’(‰"&b’òø2æçVÂ"6×ÆS×¶ç&—6µ6×ÆWÒóà¢Å…&”ÖWG&–2Æ&VÃÒ$Ö‚G&vF÷vâ"fÇVS×¶æG&vF÷vãòæÖ‡ÒW&6VçB&V6öã×¶çW&f÷&Öæ6Rç&V6öçÒf÷&×VÆÒ&Ö–â…n()ÂòÖ‚…n(((
en()Â’(‰"’"6×ÆS×·6×ÆWÒóà¢Å…&”ÖWG&–2Æ&VÃÒ%÷'FföÆ–ò&WF"fÇVS×¶æ&Væ6†Ö&²æ&WFÒ&V6öã×¶æ&Væ6†Ö&²æö'6W'fF–öç2Â#ò}	İ]Mí--í}İâíRİ½íM]İ’&Væ6†Ö&²âr¢çVÆÇÒf÷&×VÆÒ$6÷b‡.()¢Â.Zb’òf"‡.Zb’"6×ÆS×¶G¶æ&Væ6†Ö&²æö'6W'fF–öç7Ò&Væ6†Ö&²ö'6W'fF–öç6Òóà¢Å…&”ÖWG&–2Æ&VÃÒ$F—fW'6–f–6F–öâ&F–ò"fÇVS×¶æ7W'&VçE&—6³òæF—fW'6–f–6F–öå&F–÷Ò&V6öã×¶7W'&VçE&—6µ&V6öçÒf÷&×VÆÒ,ê2‡~Z"9rø>Z"’òø>()¢"6×ÆS×¶æÖG&—…6×ÆWÒóà¢Å…&”ÖWG&–2Æ&VÃÒ$VffV7F—fR†öÆF–æw2"fÇVS×¶æ6öæ6VçG&F–öãòæVffV7F—fU÷6—F–öç7Ò&V6öã×²æ6öæ6VçG&F–öâò}	İ=mİ²ıí½İ½R-]­=R½İí}İ½R-]âr¢çVÆÇÒf÷&×VÆÒ#òê2‡~Z,+"’"6×ÆSÒ-
-]­=R½İí}İ½R-]"óà¢ÂöF—cà¢Â÷6V7F–öãà¢Ç6V7F–öâ6Æ74æÖSÒ'‡&’Öw&–B#à¢Æ'F–6ÆR6Æ74æÖSÒ&6&B‡&’Ö6öæ6VçG&F–öâ#ãÆF—b6Æ74æÖSÒ'6V7F–öâÖ†VF–ær#ãÆF—cãÆƒ#í	­íİm]İ-mòıí-M]½óÂöƒ#ãÇ6Æ74æÖSÒ&6F–öâ#í
-]­=Rıí}m‚Âí-í-í-İİ½Rıâ½İí}İíÍ2-]2ãÂ÷ãÂöF—cãÇ7â6Æ74æÖSÒ'Fr#ç·vV–v‡G2æÆVæwF‡Òıí}m“Â÷7ããÂöF—cà¢²6æ6†÷BçfÇVF–öâæ6ö×ÆWFRbbÇ6Æ74æÖSÒ&æ÷F–6R#í	M½ò-í}İ½R-]í"İ=mİ²-]­=R­í-í-­‚-]Rí-­½-½Rıí}m’ãÂ÷çĞ¢ÆF—b6Æ74æÖSÒ'‡&’Ö†–v†Æ–v‡G2#ãÆF—cãÇ7ãäÆ&vW7B÷6—F–öãÂ÷7ããÆ#ç¶6öæ6VçG&F–öå7FG3òæÆ&vW7E÷6—F–öåvV–v‡BÓÒçVÆÂò}	İ]Mí--í}İâMİİ½Rr¢7B†6öæ6VçG&F–öå7FG2æÆ&vW7E÷6—F–öåvV–v‡B—ÓÂö#ãÂöF—cãÆF—cãÇ7ãåF÷2vV–v‡CÂ÷7ããÆ#ç¶6öæ6VçG&F–öå7FG2ò7B†6öæ6VçG&F–öå7FG2çF÷5vV–v‡B’¢}	İ]Mí--í}İâMİİ½RwÓÂö#ãÂöF—cãÆF—cãÇ7ãåF÷RvV–v‡CÂ÷7ããÆ#ç¶6öæ6VçG&F–öå7FG2ò7B†6öæ6VçG&F–öå7FG2çF÷UvV–v‡B’¢}	İ]Mí--í}İâMİİ½RwÓÂö#ãÂöF—cãÆF—cãÇ7ãä„„“Â÷7ããÆ#ç¶6öæ6VçG&F–öå7FG3òæ††’ÓÒçVÆÂò}	İ]Mí--í}İâMİİ½Rr¢6öæ6VçG&F–öå7FG2æ††’çFôf—†VBƒ2—ÓÂö#ãÂöF—cãÂöF—cà¢ÆF—b6Æ74æÖSÒ'‡&’Ö&'2#ç·vV–v‡G2æÖ‡ÓâÆF—b6Æ74æÖSÒ'‡&’Ö&"×&÷r"¶W“×·ç7–Ö&öÇÓãÆ#ç·ç7–Ö&öÇÓÂö#ãÆF—b6Æ74æÖSÒ'‡&’Ö&"×G&6²#ãÆ’7G–ÆS×·²v–GFƒ¢G´ÖF‚æÖ‚ƒÂÖF‚æÖ–âƒÂ‡çvV–v‡Bóò’¢’—ÒV×ÒóãÂöF—cãÇ7ãç·çvV–v‡BÓÒçVÆÂò~(	Br¢G²‡çvV–v‡B¢’çFôf—†VBƒ—ÒVÓÂ÷7ããÇ6ÖÆÃç¶ÖöæW’‡æÖ&¶WEfÇVR—ÓÂ÷6ÖÆÃãÂöF—câ—ÓÂöF—cà¢Äf÷&×VÆæÖSÒ$„„’‚İMM]­--İíR}½âıí}m’"f÷&×VÆÒ$„„’Òê2‡~Z,+"’+rVffV7F—fR†öÆF–æw2Òò„„’#í
}-İâıâİíÍí-İİ½Â-]­=Â½İí}İ½Â-]Ââ„„’½}­’¢í}İ}]"í½Í=â­íİm]İ-mâãÂôf÷&×VÆà¢Âö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6&B#ãÆF—b6Æ74æÖSÒ'6V7F–öâÖ†VF–ær#ãÆF—cãÆƒ#í
-=­-=­Âöƒ#ãÇ6Æ74æÖSÒ&6F–öâ#í	-]­ı-½-İ-]-òMí½]’ıí-M]½Íİí’f&–æ6RãÂ÷ãÂöF—cãÇ7â6Æ74æÖSÒ'Fr#ç¶2ç&—6´†÷&—¦öçÓÂ÷7ããÂöF—cà¢²æ7W'&VçE&—6²bbÇ6Æ74æÖSÒ&æ÷F–6R#ç¶7W'&VçE&—6µ&V6öçÓÂ÷çĞ¢¶æ7W'&VçE&—6²bbÆF—b6Æ74æÖSÒ'‡&’×&—6²ÖÆ—7B#ç·vV–v‡G2æÖ‡Óâ²6öç7B&2Òç&—6´6öçG&–'WF–öã²&WGW&âÆF—b6Æ74æÖSÒ'‡&’×&—6²×&÷r"¶W“×·ç7–Ö&öÇÓãÆ#ç·ç7–Ö&öÇÓÂö#ãÇ7ãí	-]Ç7G&öæsç·çvV–v‡BÓÒçVÆÂò~(	Br¢7B‡çvV–v‡B—ÓÂ÷7G&öæsãÂ÷7ããÇ7ãí
¢Ç7G&öæsç·&2ÓÒçVÆÂò~(	Br¢7B‡&2—ÓÂ÷7G&öæsãÂ÷7ããÆF—b6Æ74æÖSÒ'‡&’×&—6²Ö&'2#ãÆ’7G–ÆS×·²v–GFƒ¢G·çvV–v‡BÓÒçVÆÂò¢ÖF‚æÖ–âƒÂÖF‚æÖ‚ƒÂçvV–v‡B¢’—ÒV×ÒóãÆ’7G–ÆS×·²v–GFƒ¢G·&2ÓÒçVÆÂò¢ÖF‚æÖ–âƒÂÖF‚æÖ‚ƒÂ&2¢’—ÒV×ÒóãÂöF—cãÂöF—câÒ—ÓÂöF—cçĞ¢Ç6Æ74æÖSÒ&6F–öâ#í
İ’(	B-]²Mí½]-í-½’(	B-­½B"f&–æ6Râ	Mİİ½S¢¶æÖG&—…6×ÆWÒãÂ÷à¢Âö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6&B#ãÆƒ#í	M-]M­móÂöƒ#ãÆF—b6Æ74æÖSÒ'‡&’ÖF—fW'6–f–6F–öâ#ãÆF—cãÇ7ãäçVÖ&W"öb†öÆF–æw3Â÷7ããÆ#ç·6æ6†÷Bç÷6—F–öç2æÆVæwF‡ÓÂö#ãÂöF—cãÆF—cãÇ7ãäVffV7F—fR†öÆF–æw3Â÷7ããÆ#ç¶æ6öæ6VçG&F–öãòæVffV7F—fU÷6—F–öç3òçFôf—†VBƒ’óò}	İ]Mí--í}İâMİİ½RwÓÂö#ãÂöF—cãÆF—cãÇ7ãí
]Mİıò­í]½ımóÂ÷7ããÆ#ç¶æfW&vT6÷'&VÆF–öâÓÒçVÆÂò}	İ]Mí--í}İâMİİ½Rr¢æfW&vT6÷'&VÆF–öâçFôf—†VBƒ"—ÓÂö#ãÂöF—cãÆF—cãÇ7ãå÷'FföÆ–òföÆF–Æ—G“Â÷7ããÆ#ç¶æ7W'&VçE&—6³òçföÆF–Æ—G’ÓÒçVÆÂò}	İ]Mí--í}İâMİİ½Rr¢7B†æ7W'&VçE&—6²çföÆF–Æ—G’—ÓÂö#ãÂöF—cãÆF—cãÇ7ãåvV–v‡FVB76WBföÆF–Æ—G“Â÷7ããÆ#ç¶æ7W'&VçE&—6³òçvV–v‡FVDfW&vT76WEföÆF–Æ—G’ÓÒçVÆÂò}	İ]Mí--í}İâMİİ½Rr¢7B†æ7W'&VçE&—6²çvV–v‡FVDfW&vT76WEföÆF–Æ—G’—ÓÂö#ãÂöF—cãÆF—cãÇ7ãå&—6²†÷&—¦öãÂ÷7ããÆ#ç¶2ç&—6´†÷&—¦öçÓÂö#ãÂöF—cãÂöF—cà¢Äf÷&×VÆæÖSÒ$F—fW'6–f–6F–öâ&F–ò"f÷&×VÆÒ$E"Òê2‡~Z"9rø>Z"’òø>()¢#í	-]‚æçVÆ—¦VBföÆF–Æ—G’]=-òríMİí=â-½İİí=âí­İ¶2ç&—6´†÷&—¦öçÓ²6÷f&–æ6Rıí½Í}=]"í’İíİ½íM]İ’ãÂôf÷&×VÆà¢Âö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6&B#ãÆF—b6Æ74æÖSÒ'6V7F–öâÖ†VF–ær#ãÆF—cãÆƒ#í	­½í}]-½Rİ½íM]İóÂöƒ#ãÇ6Æ74æÖSÒ&6F–öâ#í
M­-²Â}-İİ½Rıâ-]­=ÂMİİ½Âıí-M]½òãÂ÷ãÂöF—cãÇ7â6Æ74æÖSÒ'Fr#äFWFW&Ö–æ—7F–3Â÷7ããÂöF—cà¢¶ö'6W'fF–öç2æÆVæwF‚òÇVÂ6Æ74æÖSÒ'‡&’Öö'6W'fF–öç2#ç¶ö'6W'fF–öç2æÖ†—FVÒÓâÆÆ’¶W“×¶—FVÒæ–GÒFF×6WfW&—G“×¶—FVÒç6WfW&—G—ÓãÇ7ãç¶—FVÒçF—FÆWÓÂ÷7ããÇç¶—FVÒæÖW76vWÓÂ÷ãÂöÆ“â—ÓÂ÷VÃâ¢Ç6Æ74æÖSÒ&6F–öâ#í	ıíí=í-½Rİ½íM]İòİR-½ı-½]İ²½âMİİ½Rıí­İ]Mí--í}İâãÂ÷çĞ¢Âö'F–6ÆSà¢ÄFFVÆ—G•æVÂ6æ6†÷C×·6æ6†÷GÒ6öçG&öÆÆW#×¶7Òóà¢Â÷6V7F–öãà¢ÂóçĞ ¢·F"ÓÓÒwW&f÷&Öæ6RrbbçW&f÷&Öæ6Rç&V6öâbb2æÆöF–ærbb€¢Ç6Æ74æÖSÒ&æ÷F–6R#ç¶çW&f÷&Öæ6Rç&V6öçÓÂ÷à¢—Ğ¢·F"ÓÓÒw&—6²rbbç&—6µ&V6öâbb2æÆöF–ærbb€¢Ç6Æ74æÖSÒ&æ÷F–6R#ç·&÷f–FW%&V6öâóòç&—6µ&V6öçÓÂ÷à¢—Ğ¢·F"ÓÓÒwW&f÷&Öæ6Rrbb€¢Ãà¢Å÷'FföÆ–ô†—7F÷'”6†'@¢6öçG&öÆÆW#×¶7Ğ¢7W'&Væ7“×·6æ6†÷Bç÷'FföÆ–òæ&6Uö7W'&Væ7—Ğ¢óà¢Ç6V7F–öâ6Æ74æÖSÒ&6&B#à¢ÆF—b6Æ74æÖSÒ&æÇ—F–72ÖÖWG&–72#à¢²€¢°¢wGw"rÀ¢v6w"rÀ¢wF÷FÅ&WGW&ârÀ¢v&W7DF’rÀ¢wv÷'7DF’rÀ¢w÷6—F—fTF—2rÀ¢væVvF—fTF—2rÀ¢Ò26öç7@¢’æÖ‚†ÖWG&–2’Óâ€¢ÄæÇ—F–74ÖWG&–0¢¶W“×¶ÖWG&–7Ğ¢ÖWG&–3×¶ÖWG&–7Ğ¢fÇVS×¶çW&f÷&Öæ6U¶ÖWG&–5×Ğ¢6×ÆS×·6×ÆWĞ¢&V6öã×¶çW&f÷&Öæ6Rç&V6öçĞ¢óà¢’—Ğ¢ÂöF—cà¢Â÷6V7F–öãà¢Ä6—FÅ7VÖÖ'’6æ6†÷C×·6æ6†÷GÒóà¢ÄÖöçF†Ç•&WGW&ç4†VFÖ ¢ÖöçF‡3×¶çW&f÷&Öæ6RæÖöçF†Ç—Ğ¢ÆöF–æs×¶2æÆöF–æwĞ¢6×ÆS×·6×ÆWĞ¢óà¢Âóà¢—Ğ¢·F"ÓÓÒw&—6²rbb€¢Ãà¢Ç6V7F–öâ6Æ74æÖSÒ&6&B#à¢ÆF—b6Æ74æÖSÒ'6V7F–öâÖ†VF–ær#à¢ÆF—cà¢Æƒ#ç¶2ç&—6´†÷&—¦öçÒ&—6²+rM­-}]­’ıí-M]½ÃÂöƒ#à¢Ç6Æ74æÖSÒ&6F–öâ#åG&ç67F–öâÖv&R&—6²-]=]"ıí½İí=â-½İİí=âí­İâ%U’õ4TÄÂÂİ]}-]-İ½’W‡FW&æÂfÆ÷r‚m]İí-½Rv2İRı]]­­-í-òM‚Míí-½í­‚ãÂ÷à¢ÂöF—cà¢Ç7â6Íy÷Ëh‘éì¶»§q«^vCáµ¢</th><th>RC %</th><th>Risk / Weight</th></tr></thead><tbody>{a.currentRisk.contributions.map(item => <tr key={item.symbol}><td>{item.symbol}</td><td>{pct(item.weight)}</td><td>{pct(item.assetVolatility)}</td><td>{pct(item.mcr)}</td><td>{pct(item.rc)}</td><td>{pct(item.normalizedRC)}</td><td>{item.riskWeightRatio == null ? 'ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…' : numeric(item.riskWeightRatio)}</td></tr>)}</tbody></table></div>
              <Formula name="Risk Budget" formula="MCRáµ¢=(Î£w)áµ¢/Ïƒâ‚š; RCáµ¢=wáµ¢Ã—MCRáµ¢; normalized RCáµ¢=RCáµ¢/Ïƒâ‚š">Ğ”Ğ¾Ğ»Ñ normalized RC ÑÑƒĞ¼Ğ¼Ğ¸Ñ€ÑƒĞµÑ‚ÑÑ Ğ¿Ñ€Ğ¸Ğ¼ĞµÑ€Ğ½Ğ¾ Ğ´Ğ¾ 100%. Ğ¥ĞµĞ´Ğ¶Ğ¸Ñ€ÑƒÑÑ‰Ğ¸Ğµ Ğ¿Ğ¾Ğ·Ğ¸Ñ†Ğ¸Ğ¸ Ğ¼Ğ¾Ğ³ÑƒÑ‚ Ğ¸Ğ¼ĞµÑ‚ÑŒ Ğ¾Ñ‚Ñ€Ğ¸Ñ†Ğ°Ñ‚ĞµĞ»ÑŒĞ½Ñ‹Ğ¹ Ğ²ĞºĞ»Ğ°Ğ´. Risk concentration â€” ÑÑƒĞ¼Ğ¼Ğ° ĞºĞ²Ğ°Ğ´Ñ€Ğ°Ñ‚Ğ¾Ğ² Ğ´Ğ¾Ğ»ĞµĞ¹ normalized RC, Ğ½Ğµ Ğ¿Ñ€Ğ¾Ğ³Ğ½Ğ¾Ğ· Ğ¸ Ğ½Ğµ Ñ€ĞµĞºĞ¾Ğ¼ĞµĞ½Ğ´Ğ°Ñ†Ğ¸Ñ.</Formula>
            </>}
          </section>
          <DrawdownChart analytics={a} loading={c.loading} />
          <section className="card">
            <div className="section-heading">
              <div><h2>Ğ¡ĞºĞ¾Ğ»ÑŒĞ·ÑÑ‰Ğ°Ñ Ğ²Ğ¾Ğ»Ğ°Ñ‚Ğ¸Ğ»ÑŒĞ½Ğ¾ÑÑ‚ÑŒ</h2><p className="caption">Ğ˜ÑÑ‚Ğ¾Ñ€Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ rolling-Ğ³Ñ€Ğ°Ñ„Ğ¸Ğº Ğ¸ÑĞ¿Ğ¾Ğ»ÑŒĞ·ÑƒĞµÑ‚ Ğ¾Ñ‚Ğ´ĞµĞ»ÑŒĞ½Ñ‹Ğ¹ performance period: {c.period}.</p></div>
              <PeriodSelector controller={c} />
            </div>
            <div className="chart-periods" aria-label="ĞĞºĞ½Ğ¾ Ğ²Ğ¾Ğ»Ğ°Ñ‚Ğ¸Ğ»ÑŒĞ½Ğ¾ÑÑ‚Ğ¸">
              {([20, 60, 252] as const).map((n) => (
                <button key={n} aria-pressed={volWindow === n} onClick={() => setVolWindow(n)}>{n}D</button>
              ))}
            </div>
            <AnalyticsChart key={`vol-${volWindow}-${c.period}`} points={a.rolling.volatility[volWindow]} label="Ğ¡ĞºĞ¾Ğ»ÑŒĞ·ÑÑ‰Ğ°Ñ Ğ²Ğ¾Ğ»Ğ°Ñ‚Ğ¸Ğ»ÑŒĞ½Ğ¾ÑÑ‚ÑŒ" format={pct} loading={c.loading} reason={providerReason ?? a.riskReason} />
            <Formula name="ĞĞºĞ½Ğ¾ Ğ²Ğ¾Ğ»Ğ°Ñ‚Ğ¸Ğ»ÑŒĞ½Ğ¾ÑÑ‚Ğ¸" formula="Ïƒ_window = stdev_sample(r_window) Ã— âˆš252">
              ĞÑƒĞ¶Ğ½Ğ¾ Ğ¿Ğ¾Ğ»Ğ½Ğ¾Ğµ Ğ¾ĞºĞ½Ğ¾ Ğ¸Ğ· {volWindow} Ñ‡Ğ¸ÑÑ‚Ñ‹Ñ… Ğ´Ğ¾Ñ…Ğ¾Ğ´Ğ½Ğ¾ÑÑ‚ĞµĞ¹. Ğ£Ñ‡Ğ°ÑÑ‚Ğ¾Ğº Ğ´Ğ¾ Ğ½Ğ°ĞºĞ¾Ğ¿Ğ»ĞµĞ½Ğ¸Ñ Ğ¾ĞºĞ½Ğ° Ğ¸ Ğ¾ĞºĞ½Ğ°, Ğ¿ĞµÑ€ĞµÑĞµĞºĞ°ÑÑ‰Ğ¸Ğµ Ğ¸ÑĞºĞ»ÑÑ‡Ñ‘Ğ½Ğ½Ñ‹Ğ¹ trade/gap Ğ¸Ğ½Ñ‚ĞµÑ€Ğ²Ğ°Ğ», Ğ½Ğµ Ğ²Ñ‹Ğ´ÑƒĞ¼Ñ‹Ğ²Ğ°ÑÑ‚ÑÑ. Ğ”Ğ°Ğ½Ğ½Ñ‹Ğµ: {sample}.
            </Formula>
          </section>
          <section className="card">
            <h2>Ğ¡ĞºĞ¾Ğ»ÑŒĞ·ÑÑ‰Ğ¸Ğ¹ Sharpe</h2>
            <div className="chart-periods" aria-label="ĞĞºĞ½Ğ¾ Sharpe">
              {([20, 60, 252] as const).map((n) => (
                <button key={n} aria-pressed={sharpeWindow === n} onClick={() => setSharpeWindow(n)}>{n}D</button>
              ))}
            </div>
            <AnalyticsChart key={`sharpe-${sharpeWindow}-${c.period}`} points={a.rolling.sharpe[sharpeWindow]} label="Ğ¡ĞºĞ¾Ğ»ÑŒĞ·ÑÑ‰Ğ¸Ğ¹ Sharpe" format={(v) => v.toFixed(2)} loading={c.loading} reason={providerReason ?? a.riskReason} />
            <Formula name="ĞĞºĞ½Ğ¾ Sharpe" formula="Sharpe=(252Ã—mean(r)âˆ’Rf_annual)/Ïƒ_annual">
              ĞŸĞ¾Ğ»Ğ½Ğ¾Ğµ Ğ¾ĞºĞ½Ğ¾ {sharpeWindow} Ñ‡Ğ¸ÑÑ‚Ñ‹Ñ… Ğ´Ğ¾Ñ…Ğ¾Ğ´Ğ½Ğ¾ÑÑ‚ĞµĞ¹, Rf {c.rf}% Ğ² Ğ³Ğ¾Ğ´. ĞŸÑ€Ğ¸ Ğ½ÑƒĞ»ĞµĞ²Ğ¾Ğ¹ Ğ²Ğ¾Ğ»Ğ°Ñ‚Ğ¸Ğ»ÑŒĞ½Ğ¾ÑÑ‚Ğ¸ ÑƒÑ‡Ğ°ÑÑ‚Ğ¾Ğº Ğ½ĞµĞ´Ğ¾ÑÑ‚ÑƒĞ¿ĞµĞ½. Ğ”Ğ°Ğ½Ğ½Ñ‹Ğµ: {sample}.
            </Formula>
          </section>
          <section className="card">
            <div className="section-heading">
              <div><h2>Ğ˜ÑÑ‚Ğ¾Ñ€Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ñ€Ğ¸ÑĞº Ñ‚ĞµĞºÑƒÑ‰ĞµĞ³Ğ¾ ÑĞ¾ÑÑ‚Ğ°Ğ²Ğ° Â· proxy</h2><p className="caption">ĞšĞ°Ğº ÑĞµĞ³Ğ¾Ğ´Ğ½ÑÑˆĞ½Ğ¸Ğ¹ ÑĞ¾ÑÑ‚Ğ°Ğ² Ğ¿Ğ¾Ñ€Ñ‚Ñ„ĞµĞ»Ñ Ğ²Ñ‘Ğ» Ğ±Ñ‹ ÑĞµĞ±Ñ Ğ½Ğ° Ğ¿Ñ€Ğ¾ÑˆĞ»Ñ‹Ñ… adjusted close. Ğ­Ñ‚Ğ¾ Ğ¼Ğ¾Ğ´ĞµĞ»ÑŒ, Ğ½Ğµ Ñ„Ğ°ĞºÑ‚Ğ¸Ñ‡ĞµÑĞºĞ°Ñ Ğ´Ğ¾Ñ…Ğ¾Ğ´Ğ½Ğ¾ÑÑ‚ÑŒ Ğ¿Ğ¾Ñ€Ñ‚Ñ„ĞµĞ»Ñ.</p></div>
              <span className="tag">{c.riskHorizon} Risk</span>
            </div>
            {a.proxy.riskWindow.reason && <p className="notice">{a.proxy.riskWindow.reason}</p>}
            <div className="analytics-metrics">
              <AnalyticsMetric metric="volatility" value={a.proxy.volatility} sample={`${c.riskHorizon} Â· ${a.proxy.riskWindow.availableObservations}/${a.proxy.riskWindow.required} proxy-Ğ¸Ğ½Ñ‚ĞµÑ€Ğ²Ğ°Ğ»Ğ¾Ğ²`} reason={a.proxy.riskWindow.reason} />
              <AnalyticsMetric metric="sharpe" value={a.proxy.sharpe} sample={`${c.riskHorizon} proxy Â· Rf ${c.rf}%`} ratio reason={a.proxy.riskWindow.reason} />
              <AnalyticsMetric metric="maxDrawdown" value={a.proxy.drawdown?.max} sample="Ğ¿Ğ¾Ğ»Ğ½Ğ°Ñ proxy value series; Ğ½Ğµ Risk Horizon" />
            </div>
            <Formula name="Ğ¢ĞµĞºÑƒÑ‰Ğ¸Ğµ ĞºĞ¾Ğ»Ğ¸Ñ‡ĞµÑÑ‚Ğ²Ğ°" formula="V_proxy(t) = Î£qáµ¢(today)Páµ¢(t)">
              Ğ¤Ğ¸ĞºÑĞ¸Ñ€Ğ¾Ğ²Ğ°Ğ½Ğ½Ñ‹Ğµ ÑĞµĞ³Ğ¾Ğ´Ğ½ÑÑˆĞ½Ğ¸Ğµ ĞºĞ¾Ğ»Ğ¸Ñ‡ĞµÑÑ‚Ğ²Ğ°. Ğ”Ğ¾Ñ…Ğ¾Ğ´Ğ½Ğ¾ÑÑ‚Ğ¸ ÑÑ‡Ğ¸Ñ‚Ğ°ÑÑ‚ÑÑ Ñ‚Ğ¾Ğ»ÑŒĞºĞ¾ Ğ½Ğ° return-Ğ¸Ğ½Ñ‚ĞµÑ€Ğ²Ğ°Ğ»Ğ°Ñ…, Ğ³Ğ´Ğµ Ñƒ ĞºĞ°Ğ¶Ğ´Ğ¾Ğ³Ğ¾ Ğ°ĞºÑ‚Ğ¸Ğ²Ğ° ĞµÑÑ‚ÑŒ Ğ¾Ğ±Ğµ Ñ†ĞµĞ½Ñ‹ start/end; Ğ¿Ñ€Ğ¾Ğ¿ÑƒÑĞº Ğ½Ğµ Ğ¿Ñ€ĞµĞ²Ñ€Ğ°Ñ‰Ğ°ĞµÑ‚ÑÑ Ğ² 0 Ğ¸ Ğ½Ğµ ÑĞ¾Ğ·Ğ´Ğ°Ñ‘Ñ‚ Ğ¼Ğ¾ÑÑ‚ Ñ‡ĞµÑ€ĞµĞ· Ğ´Ğ°Ñ‚Ñƒ. Ğ”Ğ»Ñ {c.riskHorizon} current-risk Ñ‚Ñ€ĞµĞ±ÑƒĞµÑ‚ÑÑ Ğ¿Ğ¾Ğ»Ğ½Ğ¾Ğµ Ğ¾ĞºĞ½Ğ¾ Ğ¸Ğ· {a.proxy.riskWindow.required} Ğ²Ğ°Ğ»Ğ¸Ğ´Ğ½Ñ‹Ñ… Ğ¸Ğ½Ñ‚ĞµÑ€Ğ²Ğ°Ğ»Ğ¾Ğ².
            </Formula>
          </section>
        </>
      )}
      {tab === 'diversification' && (
        <>
          <section className="card">
            <div className="section-heading"><div><h2>Diversification Overview</h2><p className="caption">ĞšĞ°Ğ¿Ğ¸Ñ‚Ğ°Ğ», ÑĞ¾Ğ²Ğ¼ĞµÑÑ‚Ğ½Ñ‹Ğ¹ Ñ€Ğ¸ÑĞº Ğ¸ ĞºĞ¾Ğ½Ñ†ĞµĞ½Ñ‚Ñ€Ğ°Ñ†Ğ¸Ñ risk contributions Â· {c.riskHorizon}.</p></div><span className="tag">{c.riskHorizon}</span></div>
            <div className="analytics-metrics">
              <XRayMetric label="Actual Holdings" value={snapshot.positions.length} formula="ĞšĞ¾Ğ»Ğ¸Ñ‡ĞµÑÑ‚Ğ²Ğ¾ Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚Ñ‹Ñ… Ğ¿Ğ¾Ğ·Ğ¸Ñ†Ğ¸Ğ¹" sample="Ğ¢ĞµĞºÑƒÑ‰Ğ¸Ğ¹ Ğ¿Ğ¾Ñ€Ñ‚Ñ„ĞµĞ»ÑŒ" />
              <XRayMetric label="Effective Holdings" value={a.concentration?.effectivePositions} formula="1 / Î£(wáµ¢Â²)" sample="Ğ¢ĞµĞºÑƒÑ‰Ğ¸Ğµ Ñ€Ñ‹Ğ½Ğ¾Ñ‡Ğ½Ñ‹Ğµ Ğ²ĞµÑĞ°" />
              <AnalyticsMetric metric="diversificationRatio" value={a.currentRisk?.diversificationRatio} sample={a.matrixSample} ratio reason={!a.currentRisk ? currentRiskReason : null} />
              <AnalyticsMetric metric="averageCorrelation" value={a.averageCorrelation} sample={a.matrixSample} ratio reason={!a.matrix ? matrixReason : null} />
              <XRayMetric label="Largest Position Weight" value={a.concentrationSummary?.largestPositionWeight} percent formula="max(wáµ¢)" sample="Ğ¢ĞµĞºÑƒÑ‰Ğ¸Ğµ Ñ€Ñ‹Ğ½Ğ¾Ñ‡Ğ½Ñ‹Ğµ Ğ²ĞµÑĞ°" />
              <XRayMetric label="Top 3 Weight" value={a.concentrationSummary?.top3Weight} percent formula="Î£ Ğ²ĞµÑĞ° Ñ‚Ñ€Ñ‘Ñ… ĞºÑ€ÑƒĞ¿Ğ½ĞµĞ¹ÑˆĞ¸Ñ… Ğ¿Ğ¾Ğ·Ğ¸Ñ†Ğ¸Ğ¹" sample="Ğ¢ĞµĞºÑƒÑ‰Ğ¸Ğµ Ñ€Ñ‹Ğ½Ğ¾Ñ‡Ğ½Ñ‹Ğµ Ğ²ĞµÑĞ°" />
              <XRayMetric label="Largest Risk Contributor" value={a.currentRisk?.largestRiskContributor?.contribution} percent reason={!a.currentRisk ? currentRiskReason : null} formula="max(normalized RCáµ¢)" sample={a.matrixSample} />
              <XRayMetric label="Portfolio Volatility" value={a.currentRisk?.volatility} percent reason={!a.currentRisk ? currentRiskReason : null} formula="âˆš(wáµ€Î£w)" sample={a.matrixSample} />
              <XRayMetric label="Weighted Asset Volatility" value={a.currentRisk?.weightedAverageAssetVolatility} percent reason={!a.currentRisk ? currentRiskReason : null} formula="Î£(wáµ¢ Ã— Ïƒáµ¢)" sample={a.matrixSample} />
            </div>
          </section>
          <section className="card">
            {!a.matrix && <p className="notice">{matrixReason}</p>}
            <div className="analytics-metrics">
              <AnalyticsMetric metric="covarianceVol" value={a.currentRisk?.volatility} sample={a.matrixSample} reason={!a.currentRisk ? currentRiskReason : null} />
              <AnalyticsMetric metric="diversificationRatio" value={a.currentRisk?.diversificationRatio} sample={a.matrixSample} ratio reason={!a.currentRisk ? currentRiskReason : null} />
              <AnalyticsMetric metric="averageCorrelation" value={a.averageCorrelation} sample={a.matrixSample} ratio reason={!a.matrix ? matrixReason : null} />
              <AnalyticsMetric metric="hhi" value={a.concentration?.hhi} sample="Ñ‚ĞµĞºÑƒÑ‰Ğ¸Ğµ Ñ€Ñ‹Ğ½Ğ¾Ñ‡Ğ½Ñ‹Ğµ Ğ²ĞµÑĞ°" ratio />
              <AnalyticsMetric metric="effectivePositions" value={a.concentration?.effectivePositions} sample="Ñ‚ĞµĞºÑƒÑ‰Ğ¸Ğµ Ñ€Ñ‹Ğ½Ğ¾Ñ‡Ğ½Ñ‹Ğµ Ğ²ĞµÑĞ°" ratio />
            </div>
          </section>
          <section className="card correlation-explorer">
            <div className="section-heading"><div><h2>Correlation Explorer</h2><p className="caption">ĞšĞ¾Ñ€Ñ€ĞµĞ»ÑÑ†Ğ¸Ğ¸ Ñ‚ĞµĞºÑƒÑ‰ĞµĞ³Ğ¾ risk window Ğ¸ rolling pair correlations Ğ·Ğ° Ğ´Ğ¾ÑÑ‚ÑƒĞ¿Ğ½ÑƒÑ Ğ¸ÑÑ‚Ğ¾Ñ€Ğ¸Ñ.</p></div><label>Ğ’Ñ‹Ğ±Ñ€Ğ°Ğ½Ğ½Ñ‹Ğ¹ Ğ°ĞºÑ‚Ğ¸Ğ²<select className="input" value={c.selectedCorrelationAsset} onChange={event => { c.setSelectedCorrelationAsset(event.target.value); setSelectedCorrelationPeer(''); }}>{snapshot.positions.map(position => <option key={position.symbol} value={position.symbol}>{position.symbol}</option>)}</select></label></div>
            {!a.matrix && <p className="notice">{matrixReason}</p>}
            {a.matrix && <>
              <div className="risk-budget-summary"><div><span>Highest Correlation</span><b>{c.correlationExplorer.highest ? `${c.correlationExplorer.highest.symbol} Â· ${numeric(c.correlationExplorer.highest.value)}` : 'ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…'}</b></div><div><span>Lowest Correlation</span><b>{c.correlationExplorer.lowest ? `${c.correlationExplorer.lowest.symbol} Â· ${numeric(c.correlationExplorer.lowest.value)}` : 'ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…'}</b></div><div><span>Benchmark Â· {c.benchmark}</span><b>{c.correlationExplorer.benchmark?.value == null ? 'ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…' : numeric(c.correlationExplorer.benchmark.value)}</b></div></div>
              <div className="table-scroll"><table><thead><tr><th>ĞŸĞ°Ñ€Ğ°</th><th>Correlation</th><th>Observations</th><th>Rolling detail</th></tr></thead><tbody>{c.correlationExplorer.rows.map(row => <tr key={row.symbol}><td>{c.selectedCorrelationAsset} / {row.symbol}</td><td>{row.value == null ? 'ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…' : numeric(row.value)}</td><td>{row.observations}</td><td><button className="btn btn-ghost" aria-pressed={activeCorrelationPeer === row.symbol || (!activeCorrelationPeer && selectedCorrelationRow?.symbol === row.symbol)} onClick={() => setSelectedCorrelationPeer(row.symbol)}>ĞÑ‚ĞºÑ€Ñ‹Ñ‚ÑŒ</button></td></tr>)}{c.correlationExplorer.benchmark && <tr><td>{c.selectedCorrelationAsset} / {c.benchmark}</td><td>{c.correlationExplorer.benchmark.value == null ? 'ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…' : numeric(c.correlationExplorer.benchmark.value)}</td><td>{c.correlationExplorer.benchmark.observations}</td><td><button className="btn btn-ghost" aria-pressed={activeCorrelationPeer === c.benchmark} onClick={() => setSelectedCorrelationPeer(c.benchmark)}>ĞÑ‚ĞºÑ€Ñ‹Ñ‚ÑŒ</button></td></tr>}</tbody></table></div>
              <div className="chart-periods" aria-label="Rolling correlation window">{([20, 60, 252] as const).map(n => <button key={n} aria-pressed={correlationWindow === n} onClick={() => setCorrelationWindow(n)}>{n}D</button>)}</div>
              <AnalyticsChart points={(activeCorrelationPeer === c.benchmark ? c.correlationExplorer.benchmark?.rolling[correlationWindow] ?? [] : selectedCorrelationRow?.rolling[correlationWindow] ?? []).map(point => ({ ...point, caption: `${correlationWindow}D Â· ${point.observations} observations` }))} label={`Rolling correlation ${c.selectedCorrelationAsset} / ${activeCorrelationPeer || selectedCorrelationRow?.symbol || 'asset'}`} format={numeric} loading={c.loading} reason={`ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ ${correlationWindow} Ğ¾Ğ±Ñ‰Ğ¸Ñ… Ğ¿Ğ¾ÑĞ»ĞµĞ´Ğ¾Ğ²Ğ°Ñ‚ĞµĞ»ÑŒĞ½Ñ‹Ñ… Ğ½Ğ°Ğ±Ğ»ÑĞ´ĞµĞ½Ğ¸Ğ¹ Ğ´Ğ»Ñ rolling correlation.`} />
              <Formula name="Correlation Explorer" formula="Ï(A,B)=Cov(RA,RB)/(ÏƒAÏƒB)">Current correlation Ğ¸ÑĞ¿Ğ¾Ğ»ÑŒĞ·ÑƒĞµÑ‚ Ğ¾Ğ±Ñ‰ÑƒÑ Ğ²Ñ‹Ğ±Ğ¾Ñ€ĞºÑƒ Ñ‚ĞµĞºÑƒÑ‰ĞµĞ³Ğ¾ risk window {c.riskHorizon} ({a.riskMatrix.commonObservations} observations). Rolling correlation Ğ¸ÑĞ¿Ğ¾Ğ»ÑŒĞ·ÑƒĞµÑ‚ {correlationWindow} Ñ‚Ğ¾Ñ‡Ğ½Ñ‹Ñ… Ğ¾Ğ±Ñ‰Ğ¸Ñ… Ğ¿Ğ¾ÑĞ»ĞµĞ´Ğ¾Ğ²Ğ°Ñ‚ĞµĞ»ÑŒĞ½Ñ‹Ñ… Ğ´Ğ½ĞµĞ²Ğ½Ñ‹Ñ… Ğ¸Ğ½Ñ‚ĞµÑ€Ğ²Ğ°Ğ»Ğ¾Ğ²; Ğ¿Ñ€Ğ¾Ğ¿ÑƒÑĞºĞ¸ Ğ½Ğµ Ğ·Ğ°Ğ¿Ğ¾Ğ»Ğ½ÑÑÑ‚ÑÑ.</Formula>
            </>}
          </section>
          <CorrelationMatrix matrix={a.matrix} loading={c.loading} reason={matrixReason} />
          <section className="card">
            <div className="section-heading"><h2>Ğ’ĞºĞ»Ğ°Ğ´ Ğ² Ñ€Ğ¸ÑĞº Ñ‚ĞµĞºÑƒÑ‰ĞµĞ³Ğ¾ ÑĞ¾ÑÑ‚Ğ°Ğ²Ğ°</h2><span className="tag">{c.riskHorizon}</span></div>
            {!a.currentRisk && <p className="notice">{currentRiskReason}</p>}
            <div className="table-scroll">
              <table>
                <thead><tr><th>ĞĞºÑ‚Ğ¸Ğ²</th><th>Ğ’ĞµÑ</th><th>Ğ”Ğ¾Ğ»Ñ variance</th><th>MCR = (Î£w)áµ¢</th><th>RC = wáµ¢MCRáµ¢</th></tr></thead>
                <tbody>
                  {a.currentRisk?.contributions.map((item) => (
                    <tr key={item.symbol}>
                      <td>{item.symbol}</td><td>{pct(item.weight)}</td><td>{pct(item.fraction)}</td><td>{item.marginal.toFixed(6)}</td><td>{item.absolute.toFixed(6)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <Formula name="Ğ Ğ°Ğ·Ğ»Ğ¾Ğ¶ĞµĞ½Ğ¸Ğµ variance" formula="ÏƒpÂ²=wâ€²Î£w; MCRáµ¢=(Î£w)áµ¢; RCáµ¢=wáµ¢MCRáµ¢; shareáµ¢=RCáµ¢/ÏƒpÂ²">
              Ğ“Ğ¾Ğ´Ğ¾Ğ²Ğ°Ñ covariance matrix Ğ¿Ğ¾ÑÑ‚Ñ€Ğ¾ĞµĞ½Ğ° Ğ¿Ğ¾ Ğ¾Ğ´Ğ½Ğ¾Ğ¹ Ğ¸ Ñ‚Ğ¾Ğ¹ Ğ¶Ğµ Ğ²Ñ‹Ğ±Ğ¾Ñ€ĞºĞµ Ğ¸Ğ· Ğ¿Ğ¾ÑĞ»ĞµĞ´Ğ½Ğ¸Ñ… {a.riskMatrix.required} Ğ¾Ğ±Ñ‰Ğ¸Ñ… return-Ğ¸Ğ½Ñ‚ĞµÑ€Ğ²Ğ°Ğ»Ğ¾Ğ² Ğ´Ğ»Ñ Ğ²ÑĞµÑ… Ğ°ĞºÑ‚Ğ¸Ğ²Ğ¾Ğ². Î£RCáµ¢ = ÏƒpÂ², Ğ° ÑÑƒĞ¼Ğ¼Ğ° Ğ´Ğ¾Ğ»ĞµĞ¹ RC Ñ€Ğ°Ğ²Ğ½Ğ° 1 Ñ Ñ‡Ğ¸ÑĞ»ĞµĞ½Ğ½Ğ¾Ğ¹ Ğ¿Ğ¾Ğ³Ñ€ĞµÑˆĞ½Ğ¾ÑÑ‚ÑŒÑ. ĞÑ‚Ñ€Ğ¸Ñ†Ğ°Ñ‚ĞµĞ»ÑŒĞ½Ñ‹Ğ¹ Ğ²ĞºĞ»Ğ°Ğ´ Ğ²Ğ¾Ğ·Ğ¼Ğ¾Ğ¶ĞµĞ½ Ñƒ Ñ…ĞµĞ´Ğ¶Ğ¸Ñ€ÑƒÑÑ‰ĞµĞ³Ğ¾ Ğ°ĞºÑ‚Ğ¸Ğ²Ğ°. Ğ”Ğ°Ğ½Ğ½Ñ‹Ğµ: {a.matrixSample}.
            </Formula>
          </section>
        </>
      )}
      {tab === 'attribution' && <AttributionPanel analytics={a} currency={snapshot.portfolio.base_currency} />}
      {tab === 'scenarios' && <ScenariosPanel snapshot={snapshot} />}
      {tab === 'benchmark' && <BenchmarkPanel controller={c} detailed />}
    </>
  );
}

function XRayMetric({ label, value, percent = false, reason, formula, sample }: { label: string; value: number | null | undefined; percent?: boolean; reason?: string | null; formula: string; sample: string }) {
  const display = value == null || !Number.isFinite(value) ? 'ĞĞµĞ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…' : percent ? pct(value) : numeric(value);
  return <div className="xray-summary-metric"><span>{label}<Formula name={label} formula={formula}>{reason ?? 'ĞœĞµÑ‚Ñ€Ğ¸ĞºĞ° Ñ€Ğ°ÑÑÑ‡Ğ¸Ñ‚Ğ°Ğ½Ğ° Ğ¸Ğ· ÑÑƒÑ‰ĞµÑÑ‚Ğ²ÑƒÑÑ‰ĞµĞ³Ğ¾ analytics layer.'} Ğ”Ğ°Ğ½Ğ½Ñ‹Ğµ: {sample}.</Formula></span><b title={value == null ? reason ?? undefined : undefined}>{display}</b></div>;
}
